
version: '3.3'

services:
  app1:
    image: nginx:alpine
    ports:
     - "8811:80"
    volumes:
     - ./examples/app1:/usr/share/nginx/html
  app2:
    image: nginx:alpine
    ports:
     - "8812:80"
    volumes:
     - ./examples/app2:/usr/share/nginx/html
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  proxy:
    image: envoyproxy/envoy-alpine
    ports:
     - "8815:9901"
     - "8816:10000"
    configs:
     - source: envoy_config
       target: /etc/envoy/envoy.yaml

configs:
  envoy_config:
    file: ./config/envoy.yaml


# docker container run -d -p 9901:9901 -p 10000:10000 --name envoy -v C:/Workspace/github.com/envoy-tutorial/envoy.yaml:/etc/envoy/envoy.yaml envoyproxy/envoy-alpine
